"""add_personalization_profile_fields

Revision ID: 68b49eb17d87
Revises: add_auth_fields
Create Date: 2025-12-04 17:11:28.947252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b49eb17d87'
down_revision: Union[str, Sequence[str], None] = 'add_auth_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('hardware_type', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('hardware_specs', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('has_gpu', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('has_robot_kit', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('robot_kit_type', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('education_level', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('coding_experience', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('robotics_experience', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('ml_experience', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('ros_experience', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('programming_languages', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('learning_goals', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_pace', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('time_commitment', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('areas_of_interest', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'areas_of_interest')
    op.drop_column('users', 'time_commitment')
    op.drop_column('users', 'preferred_pace')
    op.drop_column('users', 'learning_goals')
    op.drop_column('users', 'programming_languages')
    op.drop_column('users', 'ros_experience')
    op.drop_column('users', 'ml_experience')
    op.drop_column('users', 'robotics_experience')
    op.drop_column('users', 'coding_experience')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'robot_kit_type')
    op.drop_column('users', 'has_robot_kit')
    op.drop_column('users', 'has_gpu')
    op.drop_column('users', 'hardware_specs')
    op.drop_column('users', 'hardware_type')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
